import { ChangeEvent, useMemo, useState } from 'react'
import { FileText, Upload } from 'lucide-react'
import { api } from './api'
import './ResumeImport.css'

type Candidate = { name:string; phone:string|null; email:string|null; school:string|null; major:string|null; highest_degree:string|null; graduation_year:number|null; current_city:string|null }
type Option = { id:number; name:string; phone?:string; email?:string; school?:string; graduation_year?:number; applications:{id:number;job_title:string}[] }
type Preview = { resume_id:number; filename:string; status:string; text_preview:string; candidate:Candidate; confidence:Record<string,number>; warnings:string[]; match:{strong_candidate_id?:number;identity_conflict?:boolean;strong_candidates:Option[];weak_candidates:Option[]} }
const labels:Record<keyof Candidate,string>={name:'姓名',phone:'手机号',email:'邮箱',school:'学校',major:'专业',highest_degree:'最高学历',graduation_year:'毕业年份',current_city:'当前城市'}

export default function ResumeImport({jobId,close,notify,refresh,manual}:{jobId:number;close:()=>void;notify:(text:string)=>void;refresh:()=>void;manual:()=>void}) {
  const [preview,setPreview]=useState<Preview|null>(null),[form,setForm]=useState<Candidate>({name:'',phone:null,email:null,school:null,major:null,highest_degree:null,graduation_year:null,current_city:null}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selectedId,setSelectedId]=useState<number|undefined>(),[createNew,setCreateNew]=useState(false)
  const options=useMemo(()=>preview?[...preview.match.strong_candidates,...preview.match.weak_candidates]:[],[preview])
  const upload=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;setBusy(true);setError('');try{const body=new FormData();body.append('file',file);const result=await api<Preview & {message?:string}>(`/jobs/${jobId}/resume-imports/preview`,{method:'POST',body});if(result.status==='already_exists'){notify(result.message||'该简历已存在');close();return}setPreview(result);setForm({...result.candidate,name:result.candidate.name??''})}catch(reason){setError(reason instanceof Error?reason.message:'简历解析失败')}finally{setBusy(false);event.target.value=''}}
  const abandon=async()=>{if(preview&&!window.confirm('放弃本次导入？已上传的简历草稿将被删除。'))return;if(preview)await api(`/resume-imports/${preview.resume_id}`,{method:'DELETE'}).catch(()=>undefined);close()}
  const confirm=async()=>{if(!preview||!form.name.trim()){setError('请填写候选人姓名。');return}setBusy(true);setError('');try{await api(`/resume-imports/${preview.resume_id}/confirm`,{method:'POST',body:JSON.stringify({...form,graduation_year:form.graduation_year?Number(form.graduation_year):null,candidate_id:selectedId??null,create_new:createNew})});notify('候选人已通过简历导入');refresh();close()}catch(reason){setError(reason instanceof Error?reason.message:'确认导入失败')}finally{setBusy(false)}}
  const update=(key:keyof Candidate,value:string)=>setForm(current=>({...current,[key]:key==='graduation_year'?(value?Number(value):null):(value||null)}))
  if(!preview)return <div className="modal-backdrop"><div className="modal resume-modal"><div className="modal-head"><h2>上传简历</h2><button className="icon-button" onClick={close}>×</button></div><div className="tabs"><button onClick={manual}>手动填写</button><button className="selected">上传简历</button></div><p className="modal-sub">仅支持未加密、可复制文字的 PDF（10 MB、30 页以内）</p><label className="resume-drop"><Upload size={24}/><b>{busy?'正在上传并解析…':'选择 PDF 简历'}</b><small>点击选择文件</small><input type="file" accept="application/pdf,.pdf" onChange={upload} disabled={busy}/></label>{error&&<div className="resume-error">{error}<button onClick={manual}>改为手动填写</button></div>}<div className="modal-actions"><button className="secondary" onClick={close}>取消</button></div></div></div>
  return <div className="modal-backdrop"><div className="modal resume-modal"><div className="modal-head"><h2>简历识别结果</h2><button className="icon-button" onClick={abandon}>×</button></div><p className="modal-sub"><FileText size={15}/> {preview.filename} · 自动识别结果仅作为草稿，请确认后添加。</p>{options.length>0&&<div className="match-box"><b>{preview.match.identity_conflict?'身份信息冲突，请明确选择：':preview.match.strong_candidate_id?'已识别到已有候选人：':'疑似重复候选人：'}</b>{options.map(option=><label className="match-option" key={option.id}><input type="radio" name="candidate" checked={selectedId===option.id} onChange={()=>{setSelectedId(option.id);setCreateNew(false)}}/><span>{option.name} · {option.school||'学校未填'} · {option.graduation_year||'—'}<small>{option.phone||'无手机'} · {option.email||'无邮箱'} · {option.applications.map(a=>a.job_title).join('、')||'暂无投递'}</small></span></label>)}{(preview.match.identity_conflict||preview.match.weak_candidates.length>0)&&<label className="match-option"><input type="radio" name="candidate" checked={createNew} onChange={()=>{setCreateNew(true);setSelectedId(undefined)}}/><span>仍新建候选人</span></label>}</div>}{(Object.keys(labels) as (keyof Candidate)[]).map(key=><label key={key} className={['name','major','current_city'].includes(key)&&(preview.confidence[key]||0)<0.7?'low-confidence':''}>{labels[key]}{key==='name'&&<sup>*</sup>}<input value={form[key]??''} onChange={event=>update(key,event.target.value)} placeholder={key==='name'?'请填写姓名':'未识别，可手动补充'}/>{['name','major','current_city'].includes(key)&&(preview.confidence[key]||0)<0.7&&<small>建议人工确认</small>}</label>)}{preview.warnings.length>0&&<div className="resume-warnings">{preview.warnings.join('；')}</div>}<details className="resume-text-preview"><summary>查看识别到的简历原文（可复制）</summary><pre>{preview.text_preview}</pre></details>{error&&<div className="resume-error">{error}</div>}<div className="modal-actions"><button className="secondary" onClick={abandon}>取消</button><button className="primary" disabled={busy||!form.name.trim()} onClick={confirm}>{busy?'正在确认…':'确认添加'}</button></div></div></div>
}
